### ISSUE TITLE
"Overwrite of data FAILED" on "Partition/entire disk"

### ISSUE THREAD

**Issue by albionxyz** [t-d-k/LibreCrypt#42]
In the "New Container Wizard" when I select "Partition/entire disk" and click on Finish following error message appears: "Overwrite of data FAILED."

**Comment by t-d-k** [comment]
Thanks for reporting this, it has been fixed in the latest build.  
It should work with [this build](https://github.com/t-d-k/LibreCrypt/releases/tag/6.3)

**Comment by albionxyz** [comment]
The link refers to 6.3alpha on which my bugreport referred to (also on 6.2). Unfortunately, it is not fixed yet.

**Comment by dominet** [comment]
It seems that 6.3 still has this bug and I am unable to encrypt the whole DATA (not the boot) partition on a Windows10 system. When clicking finish I get an error 'Overwrite of data FAILED', and there is no possibility to continue to anywhere. Please let me know what am I doing wrong... Thanks.

**Comment by Jotune** [comment]
Any update on this ?

**Comment by Fruchtzwerg94** [comment]
Still having the same error.
